<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Boton aceptar cokies</name>
   <tag></tag>
   <elementGuidId>4d5dcd44-f912-4b1e-a3c2-7e0a6be03215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sp-cc-accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sp-cc-accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0e38655-0e03-4c62-ab09-6d259340eca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sp-cc-accept</value>
      <webElementGuid>85f79e26-c77a-4824-a14f-d527debc8868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3ee48d6f-b6b8-4704-ad86-d003c0b79549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accept</value>
      <webElementGuid>f40c815d-b2da-4d41-acf7-3216f48dc5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input celwidget</value>
      <webElementGuid>0607c4eb-cc5a-4836-be44-0d7df7074440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ad9a09e6-1ab9-4002-b2c1-86bdc9cf25a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>all</value>
      <webElementGuid>af895e06-febf-436a-a366-114127a9eb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>rxojgb-vezc9e-naz7n8-d8gque</value>
      <webElementGuid>6c883902-516d-46a0-b341-cb03bac830fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-0-announce</value>
      <webElementGuid>3e14ccda-b923-43bc-a309-a53f3bf3d227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cel-widget</name>
      <type>Main</type>
      <value>sp-cc-accept</value>
      <webElementGuid>e61cc4dc-a77e-4cac-aafb-d3f0dab5c63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sp-cc-accept&quot;)</value>
      <webElementGuid>194f0770-e19a-4d3a-aa4f-57081ccbcb6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sp-cc-accept']</value>
      <webElementGuid>257f7f2e-547b-47ee-bb9d-0a201611a93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0']/span/input</value>
      <webElementGuid>20f46a54-af9b-4cd2-ae10-ac41597bb9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>82995f00-fb13-4eb6-a026-06f3d899e6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sp-cc-accept' and @name = 'accept' and @type = 'submit']</value>
      <webElementGuid>b7262ba2-0ea7-43e0-97d4-f394f78e3811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
