<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>boton continuar sin aceptar cookies</name>
   <tag></tag>
   <elementGuidId>bf2bb518-a537-4b34-a442-9dbb5bd586d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sp-cc-rejectall-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sp-cc-rejectall-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22c6aaad-18f5-4bd0-9132-424e1e67699c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sp-cc-rejectall-link</value>
      <webElementGuid>43ca3d82-004a-4bd1-8290-246f3cf7695a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-emphasis</value>
      <webElementGuid>4d686bb6-99cc-499e-a79a-dc38bbaf362c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>04fb9b43-bd24-48f2-b877-f48ee1e33310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1431648-2241-4340-b056-f16c7320ace9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar sin aceptar</value>
      <webElementGuid>7a691660-7124-4607-8cf6-26815c620a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sp-cc-rejectall-link&quot;)</value>
      <webElementGuid>3f86d9b5-f366-4ee8-8344-9aaed4818c96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sp-cc-rejectall-link']</value>
      <webElementGuid>13cdc61a-4113-45ac-977d-682fe6767b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sp-cc-rejectall-container']/a</value>
      <webElementGuid>7b372941-ce08-46b9-931d-a2648425b608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continuar sin aceptar')]</value>
      <webElementGuid>eb24ff29-9ca3-45a7-a040-16dee779dd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona Tus Preferencias de Cookies'])[1]/preceding::a[1]</value>
      <webElementGuid>aeaa84d4-6164-43b8-b52e-6b3eaa1d53b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aviso de cookies'])[1]/preceding::a[1]</value>
      <webElementGuid>42ce138d-fedd-48f5-8846-071688858ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuar sin aceptar']/parent::*</value>
      <webElementGuid>5d174498-3ed7-4455-993b-531214d52650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>215d426c-65f0-444b-bac6-eadb33b39823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>e227778d-e27d-40ce-b121-43b1b5acb39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sp-cc-rejectall-link' and @href = '#' and (text() = 'Continuar sin aceptar' or . = 'Continuar sin aceptar')]</value>
      <webElementGuid>75f7d68f-6354-4f2e-ba8b-c617ec9da910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
