<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite Cesta</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>43c4b2a4-f112-4f59-8ead-ee19ce596f57</testSuiteGuid>
   <testCaseLink>
      <guid>d1803748-c2d2-4d5b-9898-ee8f2ab2341e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cesta/Anadir objetos a cesta y borrarlos despues</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3cbb408-6439-430d-bc09-8717f2ba7799</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>060505f2-8bd5-4309-a62d-0eb3b9386800</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a869756-6b2c-49e5-80c6-685cb6dfd750</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cesta/Anadir objetos a cesta - logearse - fusionar cestas - borrarlos despues</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>318acfd6-5443-4fb4-a1b8-89eb45d2cc5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>878e64ec-b18a-4e44-a2fe-2fb3a956ede6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>333a0247-f457-4829-85d2-9056de9973ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48430e48-7475-4289-936a-213d5da14577</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f875878c-48e2-4ba2-9592-30fe03cc8fad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cesta/Anadir objetos a cesta</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a413c956-b0cd-42bb-ac9a-3479d189be23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4409e14a-c3e6-4dee-8132-03047dab6cb6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b27c4ccf-7d53-4260-9d0f-36059824ccdd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cesta/Borrar objetos de cesta vacia</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03167d35-9e59-4111-99a9-9346de5e087d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2ceabdc-b96b-4484-a79a-4d4478ab7616</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d16fcf7b-dbfa-4f42-aeb8-6432022b2c17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cesta/Loguearse - Anadir objetos - Desloguearse - Anadir objetos - Loguearse - Fusionar Cestas - borrarlos despues</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53b46e7f-d727-4941-9f16-65eec6b1a6fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c080791-19d9-4027-a5d8-89730fd730b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e1fc048-828d-4af4-b12d-a0f686e26a68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a29c65c2-f43d-4d27-9b25-a45fae54b86f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b66d5969-d018-4feb-9219-02858779b726</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
