<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Boton eliminar direccion</name>
   <tag></tag>
   <elementGuidId>3ac10f5c-9261-4ebc-9977-0ec954f936a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ya-myab-address-delete-btn-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ya-myab-address-delete-btn-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6354e70f-26a8-447d-9d32-efb709c85c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ya-myab-address-delete-btn-0</value>
      <webElementGuid>5952c8d7-fd41-41a5-bf3b-d4493a5931a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal delete-link</value>
      <webElementGuid>20c79649-c81e-4b03-a5f3-c601efc84206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f567784d-407d-42a1-b454-5be9e54960be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descartar</value>
      <webElementGuid>e449023f-8051-4ac6-b2fe-12eeb9bff1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ya-myab-address-delete-btn-0&quot;)</value>
      <webElementGuid>4db91e2a-acc8-46b0-99e2-3436f779f99c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ya-myab-address-delete-btn-0']</value>
      <webElementGuid>d0291879-e309-4c04-b4dd-8bd642d45193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ya-myab-edit-address-desktop-row-0']/span/a</value>
      <webElementGuid>b724fc5f-5005-4785-90c1-8aacf271a301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Descartar')]</value>
      <webElementGuid>47b78ef8-d495-4dec-9244-8aa3c3b674e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[1]/following::a[1]</value>
      <webElementGuid>1f4c874f-7fa2-4d57-b6d3-bf8c09dc00c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba Katalon Oscar Marcos'])[2]/preceding::a[1]</value>
      <webElementGuid>e0e951e9-9957-4872-b348-02c88d65d402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avenida Cantabria'])[2]/preceding::a[1]</value>
      <webElementGuid>6cdc12f7-9486-41c2-bcc2-4bccf7cf18e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descartar']/parent::*</value>
      <webElementGuid>31a4b986-1702-42a5-944e-8c4cf7fc7146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>4f1bd135-a17f-48b6-abde-96ac4f69013a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/a</value>
      <webElementGuid>30b25086-bef5-4f6f-b98c-3f278c0e1011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ya-myab-address-delete-btn-0' and @href = '#' and (text() = 'Descartar' or . = 'Descartar')]</value>
      <webElementGuid>0c38427c-1b39-4f14-ad5e-6966ff6b8a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
