<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Boton confirmar direccion</name>
   <tag></tag>
   <elementGuidId>18cf727c-57ee-4a50-9af1-da951fa92765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='address-ui-widgets-form-submit-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address-ui-widgets-form-submit-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>269f740e-84f9-4243-ad79-c62d0de1980f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-ui-widgets-form-submit-button</value>
      <webElementGuid>8cce032c-118b-4a92-a142-082f0bc09854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-primary</value>
      <webElementGuid>6fd91414-51f8-4cc3-adb3-72c1a96df85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Añadir dirección</value>
      <webElementGuid>ba0b8856-9973-4ce1-be99-bf2c67b873f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-form-submit-button&quot;)</value>
      <webElementGuid>c89ac8a2-dd64-4017-82ef-cfe71713501d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='address-ui-widgets-form-submit-button']</value>
      <webElementGuid>cc9f3e1b-8d96-45ff-98bb-acea469c2a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/span[3]/span</value>
      <webElementGuid>346fe789-df28-4871-8454-fac3c0ae7161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se produjo un problema al cargar las instrucciones de entrega. Inténtalo de nuevo.'])[1]/following::span[2]</value>
      <webElementGuid>ffe01d65-d827-45a4-bba1-4346c31c5845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir instrucciones de entrega'])[1]/following::span[2]</value>
      <webElementGuid>24596ab5-1f69-4519-8f54-6de92ed92388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más productos digitales para explorar'])[1]/preceding::span[3]</value>
      <webElementGuid>f7c12920-9894-4141-b2bf-96e230923e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span</value>
      <webElementGuid>0293346c-d81f-4d40-998c-34b564e33d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'address-ui-widgets-form-submit-button' and (text() = 'Añadir dirección' or . = 'Añadir dirección')]</value>
      <webElementGuid>09af9489-3c4e-4590-88dd-d29fa0644594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
