<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Boton descartar</name>
   <tag></tag>
   <elementGuidId>2be0cc6c-cd98-4394-8e92-b2b0c25d1865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ya-myab-address-delete-btn-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ya-myab-address-delete-btn-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c14e96a-3379-40e6-bc52-cc08491c0a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ya-myab-address-delete-btn-0</value>
      <webElementGuid>fb3c4f89-8766-4ec8-90bd-ae3036dd484a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal delete-link</value>
      <webElementGuid>8f49f17a-298d-4ed4-81d2-ee7edeaff078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8522b81d-1a0f-4ead-9555-bf3018d543d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descartar</value>
      <webElementGuid>7b9d9918-30c1-4e8b-9259-631fc57d86e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ya-myab-address-delete-btn-0&quot;)</value>
      <webElementGuid>4b11380c-52ee-424c-9331-b3e8e8e72bb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ya-myab-address-delete-btn-0']</value>
      <webElementGuid>366912e5-e426-4884-bacf-aabc3da41147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ya-myab-edit-address-desktop-row-0']/span/a</value>
      <webElementGuid>1e979286-1172-487d-a046-cfea0a622756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Descartar')]</value>
      <webElementGuid>6c568284-84cc-4249-98da-cdba778314b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[1]/following::a[1]</value>
      <webElementGuid>0022a879-4b6a-4778-8597-3244e817f6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba Katalon Oscar Marcos'])[2]/preceding::a[1]</value>
      <webElementGuid>90b125c2-495f-4b94-97ee-17c81b76a3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avenida Cantabria'])[2]/preceding::a[1]</value>
      <webElementGuid>3a309a43-6d71-4f5d-a92d-ac3c23518858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Descartar']/parent::*</value>
      <webElementGuid>a720ef57-ffe4-470b-8af4-4f990ee977ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>9c1d51be-5873-447c-8d99-38b338b73b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/a</value>
      <webElementGuid>53139f7a-743b-4c48-ab43-b5530553f31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ya-myab-address-delete-btn-0' and @href = '#' and (text() = 'Descartar' or . = 'Descartar')]</value>
      <webElementGuid>db793ff7-4e5c-4ce5-951a-273f78a0b8b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
