<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Campo si (borrar)</name>
   <tag></tag>
   <elementGuidId>d01e4caf-bb5d-4ff3-bca4-ebecdfcdff45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='deleteAddressModal-0-submit-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#deleteAddressModal-0-submit-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0262c2e8-5e3d-4455-9fca-02c68ae33e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deleteAddressModal-0-submit-btn</value>
      <webElementGuid>c799ba16-138b-4dda-ba21-9fa3af18624f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button a-button-span12 a-button-primary</value>
      <webElementGuid>4315e211-9e02-4fef-a281-d38380e74685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sí</value>
      <webElementGuid>0b4d5436-6522-4a75-8f4f-5f465e84b212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteAddressModal-0-submit-btn&quot;)</value>
      <webElementGuid>da6da9be-2597-4902-bf36-30da60335bbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='deleteAddressModal-0-submit-btn']</value>
      <webElementGuid>1749de12-b77b-4587-b8a3-6f0104ff5157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-content-3']/div/div[4]/div[2]/div/div[2]/form/span</value>
      <webElementGuid>6352e78a-06c8-452b-9fa0-9efb1c35670f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::span[1]</value>
      <webElementGuid>06a81542-4ce8-430d-9dbf-d37de871630f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nota:'])[1]/following::span[3]</value>
      <webElementGuid>1980b6dc-49e8-465b-aac6-2eee56f19da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span</value>
      <webElementGuid>49626428-ad6d-435c-9d32-849db3d0a277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'deleteAddressModal-0-submit-btn' and (text() = 'Sí' or . = 'Sí')]</value>
      <webElementGuid>5bfc0f96-90bb-4582-baf3-ff3874d943ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
