<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Error introduce un nombre de ciudad</name>
   <tag></tag>
   <elementGuidId>aa0359a9-4469-404c-a809-a8b192c043c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[11]/div[2]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.a-column.a-span8.a-span-last > div.a-section.a-spacing-none.adddress-ui-widgets-form-field-container > div.a-section.a-spacing-none.a-spacing-top-micro.address-ui-widgets-inline-error-alert > div.a-box.a-alert-inline.a-alert-inline-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f89701fd-9f0e-4daa-8b9e-76eda8c8642f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-box a-alert-inline a-alert-inline-error</value>
      <webElementGuid>7dcf4adb-95df-40c0-aa00-8956066144ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>e43aba53-794d-47a2-aae2-b0276b5c605e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>eab535a3-d5e5-4db0-8366-51fd0b7674d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Introduce un nombre de ciudad.</value>
      <webElementGuid>37a23b32-c237-441c-991f-9d313c715dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-ui-widgets-enterAddressFormContainer&quot;)/div[@class=&quot;a-row&quot;]/div[@class=&quot;a-input-text-group a-spacing-medium a-spacing-top-medium&quot;]/div[@class=&quot;a-row address-ui-widgets-mobile-two-column-form-field-view-grid-row&quot;]/div[@class=&quot;a-column a-span8 a-span-last&quot;]/div[@class=&quot;a-section a-spacing-none adddress-ui-widgets-form-field-container&quot;]/div[@class=&quot;a-section a-spacing-none a-spacing-top-micro address-ui-widgets-inline-error-alert&quot;]/div[@class=&quot;a-box a-alert-inline a-alert-inline-error&quot;]</value>
      <webElementGuid>437b9b46-79ad-4b26-973e-60290983495e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-ui-widgets-enterAddressFormContainer']/div[7]/div/div[11]/div[2]/div[2]/div/div</value>
      <webElementGuid>1b0b1acf-5b86-43fa-8566-9810bd07e184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciudad'])[1]/following::div[3]</value>
      <webElementGuid>900f734e-e091-4216-ba16-e2e5f3079371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Especifica un código postal válido.'])[1]/following::div[6]</value>
      <webElementGuid>ade99919-9ae4-4005-ad58-92ac7a6fa579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introduce un nombre de ciudad.'])[2]/preceding::div[4]</value>
      <webElementGuid>46a85a88-3645-4bcc-af54-c192b1e2fb0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>997c605b-2f55-4dab-b173-c8c77ab7f557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Introduce un nombre de ciudad.' or . = 'Introduce un nombre de ciudad.')]</value>
      <webElementGuid>0d99c19f-158c-4978-ad22-8f7eef593f3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
