<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>boton eliminar item</name>
   <tag></tag>
   <elementGuidId>b6f82fa8-1ef4-465b-86b5-8e74e940185c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.delete.C0346c065-9b0f-4699-8e58-9fa2b87e1b9d&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.delete.C0346c065-9b0f-4699-8e58-9fa2b87e1b9d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b563f6f-bd47-4b8d-a3ed-ea3c03d57b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.delete.C0346c065-9b0f-4699-8e58-9fa2b87e1b9d</value>
      <webElementGuid>8cbf061a-3fd7-451b-9fe0-18d2b4faa9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>7bdc4226-fcc9-4681-b3b0-bd33d12cd8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>delete</value>
      <webElementGuid>166da497-7add-40a3-89c6-49ee88b7a665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Eliminar YongerYong Ni&amp;ntilde;a Ni&amp;ntilde;o Zapatos con 4 Ruedas LED Luces，Roller Skate Zapatos con USB Recargable,Ruedas Retr&amp;aacute;ctil Skateboarding Rollerblades Deportes al Aire Libre Zapatos</value>
      <webElementGuid>5f1ba80c-92e6-49a3-87e7-df81f91d2115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f8a75f05-fb30-404d-832e-e5e6ba9cf5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-link</value>
      <webElementGuid>4d7b2741-a106-42f1-9f6d-1cda9b08bd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-item-C0346c065-9b0f-4699-8e58-9fa2b87e1b9d&quot;)/div[@class=&quot;sc-list-item-content&quot;]/div[@class=&quot;a-row a-spacing-base a-spacing-top-base&quot;]/div[@class=&quot;a-column a-span10&quot;]/div[@class=&quot;a-fixed-left-grid&quot;]/div[@class=&quot;a-fixed-left-grid-inner&quot;]/div[@class=&quot;a-fixed-left-grid-col a-col-right&quot;]/div[@class=&quot;a-row sc-action-links&quot;]/span[@class=&quot;a-size-small sc-action-delete&quot;]/span[@class=&quot;a-declarative&quot;]/input[@class=&quot;a-color-link&quot;]</value>
      <webElementGuid>0d9eb66c-65f0-492f-9a77-4a1486e41406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.delete.C0346c065-9b0f-4699-8e58-9fa2b87e1b9d']</value>
      <webElementGuid>6ebd0a3b-e856-4fcd-8843-df9bd635196d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-item-C0346c065-9b0f-4699-8e58-9fa2b87e1b9d']/div[4]/div/div/div/div/div[2]/div/span[2]/span/input</value>
      <webElementGuid>776cc6ce-5b29-4701-9447-d4bee8dde478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>3ec71fdf-b75a-4b31-9c77-9ce7260c005e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.delete.C0346c065-9b0f-4699-8e58-9fa2b87e1b9d' and @type = 'submit']</value>
      <webElementGuid>4b4a7d5c-1e3b-436e-93c0-b5382ade4ba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
