<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Boton cambiar email</name>
   <tag></tag>
   <elementGuidId>19b130a7-a08f-4050-bdce-239e583e50f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ap_change_login_claim</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ap_change_login_claim']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>871a342f-e77f-45da-9254-2c7b20cb2f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap_change_login_claim</value>
      <webElementGuid>6acee1ce-ba95-4525-b6fc-e011dc9ebc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal</value>
      <webElementGuid>8b9dff7d-919d-4877-9e2d-54553ae02297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>060eba3d-e559-4096-bf8e-4bc0df4fa256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.es/ap/signin?showRememberMe=true&amp;openid.pape.max_auth_age=0&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;pageId=esflex&amp;mobileBrowserWeblabTreatment=C&amp;openid.return_to=https%3A%2F%2Fwww.amazon.es%2Fref%3Dnav_signin&amp;prevRID=AZN21FRNA3ZBTG469XT5&amp;openid.assoc_handle=esflex&amp;openid.mode=checkid_setup&amp;desktopBrowserWeblabTreatment=C&amp;prepopulatedLoginId=eyJjaXBoZXIiOiIrOERFcUJFV2Z0N2hTQkNPMzVkVG9KVjVldmVoY0JGKzJNNTh4UWZDajNFPSIsInZlcnNpb24iOjEsIklWIjoicW1iMzYyV3ZWT2h5ZjVCVjZLcjkrQT09In0%3D&amp;failedSignInCount=1&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;timestamp=1666565543000</value>
      <webElementGuid>9dbba355-52d1-49b6-b115-5fb328175df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Cambiar
      </value>
      <webElementGuid>cb0426ee-811f-4739-a5ee-c55caf61f7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_change_login_claim&quot;)</value>
      <webElementGuid>9f8ae921-91ec-44e6-a840-ae87c1d824f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ap_change_login_claim']</value>
      <webElementGuid>f4298d4c-e911-411d-87c3-72bf55285c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authportal-main-section']/div[2]/div/div/div/div/a</value>
      <webElementGuid>794bd6f8-dc60-4311-8738-cfcfc0534291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cambiar')]</value>
      <webElementGuid>25c8493e-452b-4435-a350-40a5d8f4c59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='raksovalverde95@gmail.com'])[1]/following::a[1]</value>
      <webElementGuid>912a8b0d-b6e2-4dee-9f69-092db1205ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar sesión'])[1]/following::a[1]</value>
      <webElementGuid>9ff3c768-1118-43df-9b2c-dbd61f8b962e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contraseña'])[1]/preceding::a[1]</value>
      <webElementGuid>17ba89d1-70c1-4c60-8a07-1785b6639612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Has olvidado la contraseña?'])[1]/preceding::a[1]</value>
      <webElementGuid>3d7ab42c-e514-48a5-a2fc-f0e3b7d41088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cambiar']/parent::*</value>
      <webElementGuid>d8cab38d-115d-4f42-84d8-b2639f356db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.es/ap/signin?showRememberMe=true&amp;openid.pape.max_auth_age=0&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;pageId=esflex&amp;mobileBrowserWeblabTreatment=C&amp;openid.return_to=https%3A%2F%2Fwww.amazon.es%2Fref%3Dnav_signin&amp;prevRID=AZN21FRNA3ZBTG469XT5&amp;openid.assoc_handle=esflex&amp;openid.mode=checkid_setup&amp;desktopBrowserWeblabTreatment=C&amp;prepopulatedLoginId=eyJjaXBoZXIiOiIrOERFcUJFV2Z0N2hTQkNPMzVkVG9KVjVldmVoY0JGKzJNNTh4UWZDajNFPSIsInZlcnNpb24iOjEsIklWIjoicW1iMzYyV3ZWT2h5ZjVCVjZLcjkrQT09In0%3D&amp;failedSignInCount=1&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;timestamp=1666565543000')]</value>
      <webElementGuid>2988c9a4-75a7-4300-8b85-cc77563cbd63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>ed7187b7-77b3-4dfa-b4a1-bfad57c76758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ap_change_login_claim' and @href = 'https://www.amazon.es/ap/signin?showRememberMe=true&amp;openid.pape.max_auth_age=0&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;pageId=esflex&amp;mobileBrowserWeblabTreatment=C&amp;openid.return_to=https%3A%2F%2Fwww.amazon.es%2Fref%3Dnav_signin&amp;prevRID=AZN21FRNA3ZBTG469XT5&amp;openid.assoc_handle=esflex&amp;openid.mode=checkid_setup&amp;desktopBrowserWeblabTreatment=C&amp;prepopulatedLoginId=eyJjaXBoZXIiOiIrOERFcUJFV2Z0N2hTQkNPMzVkVG9KVjVldmVoY0JGKzJNNTh4UWZDajNFPSIsInZlcnNpb24iOjEsIklWIjoicW1iMzYyV3ZWT2h5ZjVCVjZLcjkrQT09In0%3D&amp;failedSignInCount=1&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;timestamp=1666565543000' and (text() = '
        Cambiar
      ' or . = '
        Cambiar
      ')]</value>
      <webElementGuid>9c2beaff-0c6e-48c5-bf3a-fab345d5017d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
